;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-buffer-menu
        mouse-set-secondary
        ))
